### ISSUE TITLE
Vídeo indisponível - Este vídeo é privado

### ISSUE THREAD

**Issue by jeffersoncbd** [filipedeschamps/BrasilAPI#1]
Libera hoje as 11h?

**Comment by gagustavo** [comment]
Neste exato momento eu tive um caso de uso para a API. Fui ver o projeto e?....

Mas tem na organization: https://github.com/BrasilAPI/BrasilAPI

**Comment by enieber** [comment]
@jeffersoncbd video liberado...

**Comment by filipedeschamps** [comment]
Boa pessoal!! Vou fechar essa issue 🤝
