### ISSUE TITLE
[Question] Usar SWR para cache

### ISSUE THREAD

**Issue by r3nanp** [filipedeschamps/BrasilAPI#108]
**Por que não usar SWR para o cache e data fetching?**

**Comment by paulogdm** [comment]
Olá :wave: 

Eu não tenho certeza como você identificou a oportunidade de usar [SWR](https://github.com/vercel/swr), que é uma lib para React.

Na API, o header `stale-while-revalidate` já está sendo usado na API e com uma eficiência bem interessante. Checa esse PR: #30

**Comment by r3nanp** [comment]
Obrigado!!
