### ISSUE TITLE
Brasil.IO (e evitar retrabalho)

### ISSUE THREAD

**Issue by turicas** [filipedeschamps/BrasilAPI#47]
Oi, pessoal, tudo bem?
Criei o Brasil.IO há alguns anos com objetivos bem parecidos com o desse projeto e estou criando essa issue para abrir um canal de comunicação com a finalidade de evitar retrabalho: o Brasil.IO já possui uma infraestrutura de hospedagem de datasets (ainda precisamos melhorar algumas coisas, mas já existe e está funcional), já possui diversos voluntários contribuindo com código e dinheiro para manter os servidores e já é utilizado por muita gente (incluindo grandes veículos de mídia).

**Comment by filipedeschamps** [comment]
Que massa @turicas ! Se eu não me engano, alguém chegou a citar o Brasil.IO em alguma das issues aqui. De qualquer forma, obrigado por abrir essa issue e aproximar a comunicação meu caro 🤝

A ideia de criar esse projeto aqui veio de uma frustração que eu e o @lucianopf temos no projeto do `cep-promise` a respeito do CORS dos Correios. Dai a ideia foi crescendo ao ponto de se misturar com a nossa vontade de estressar o Now (Zeit) cada vez mais e querer resolver um problema maior do que uma entrega de ceps e tratar sobre todas as informações do Brasil (que dai casa totalmente com a proposta do Brasil.IO) 👍 

O que eu não esperava é que esse repositório atingisse mais de 600 estrelas sem eu falar nada (acho que foi distribuindo por dentro do Github mesmo) e a turma sensacional começou a contribuir com muita força!!! Eu to surpreso até agora e não consegui dar conta de revisar tudo, me pegou de calça curta 😂 

E eu acho que essa é a parte mais importante de todas, de pessoas contribuindo com projetos... com diversos projetos na verdade, sejam eles resolvendo problemas iguais de formas diferentes, ou resolvendo problemas diferentes de formas iguais. Isso para mim é o princípio do software livre e quanto mais isso acontecer, mais pequenas coisas vão ser descobertas ao longo do caminho e que eventualmente, vão gerar cada vez mais progresso.

Com isso, na minha visão os dois projetos devem continuar rodando em paralelo, se ajudando na medida do possível, para abrir o máximo de oportunidade para pessoas entrarem no mundo open source.

O que acha?

**Comment by lucianopf** [comment]
Concordo muito com a visão do @filipedeschamps !

E acho que inclusive os projetos podem coexistir e inclusive se integrar no futuro pra aumentar a quantidade de APIs que conseguimos disponibilizar com os 2 serviços! 😬
