### ISSUE TITLE
Cache dos dados

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/BrasilAPI#6]
Indicado pelo @lucianopf parece ser uma delicinha implementar o cache control pela Smart CDN deles: https://zeit.co/docs/v2/serverless-functions/edge-caching

Tenho uma curiosidade paralela em entender como a Zeit lida com DDOS e se é necessário colocar um Clouflare na frente: https://zeit.co/docs/v1/guides/how-to-use-cloudflare

Essa issue mexe diretamente com o comportamento da issue #5 sobre persistência dos dados e quando que eles devem ser atualizados. Talvez esse cache na ponta facilite tudo, pois a lógica da lamba pode ser algo como "atualizar sempre que retornar uma resposta sem erro do serviço que eu estou consultando" e deixa o cache na ponta ser o gargalo... quando expirar, entra na lambda.

**Comment by lucianopf** [comment]
Sobre o Now e a Smart CDN: https://zeit.co/docs/v2/network/frequently-asked-questions#what-if-there-is-a-ddos-will-we-get-charged-for-the-cdn-traffic

😬 , acho que estamos ok, a migração pra CloudFlare era normal antes da CDN, hoje em dia vejo pouca movimentação nesse sentido 🤔 😬

**Comment by filipedeschamps** [comment]
Ahhh @lucianopf que sensacional!! Ótimo achado 👍 os caras são muito fera!!!

**Comment by filipedeschamps** [comment]
Isso já foi implementado e melhorado por esse PR: https://github.com/filipedeschamps/BrasilAPI/pull/30

**Comment by LorhanSohaky** [comment]
Clouflare agora está me dando block :cry:
