### ISSUE TITLE
Ótima notícia: Vercel vai ser sponsor do projeto 😍 

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/BrasilAPI#62]
Primeiro, não dá para imaginar que esse projeto esta quase chegando em 1mil stars, simplesmente sensacional o engajamento da turma! 🤩

E agora que eu consegui soltar a série de 3 vídeos sobre desenvolvimento web, os conteúdos no canal vão retomar a quantidade de produção normal e estou louco para voltar a colocar a mão na massa aqui no repositório junto com todos vocês, pois tem muitas Issues e Pull Requests importantes precisando de atenção. O @lucianopf também vai profissionalizar algumas partes, tanto que sentimos a necessidade de tirar o projeto de uma conta `hobby` minha para um `team` dentro da Vercel e a boa notícia vem exatamente ai:

**Nós nos aplicamos para o programa de apoio a projetos Open Source da Vercel e fomos aceitos!!!** 😍 

Muito obrigado especialmente ao @paulogdm por tudo o que já fez no projeto e por atender esse caso.

O projeto já foi migrado da minha conta pessoal para conta de time e o processo foi muito tranquilo, inclusive reapontar o domínio (deu para fazer tudo por dentro da Dashboard, sem precisar mexer em DNS). O bom disso é que as modificações foram aplicadas imediatamente.

E para o sponsor deles vamos adicionar alguns banners da Vercel (tanto na página quanto no repositório) identificando que o projeto está recebendo o apoio deles e eu devo fazer isso até amanhã e nisso também tem uma outra boa notícia:

**Agora o projeto tem um logo** 😍  (ou pelo menos, uma versão 0.0.1-alpha de um logo 😂)

<img src="https://user-images.githubusercontent.com/4248081/83680174-77fcfc80-a595-11ea-99b8-11f260f3e8ac.png">

E é inspirado na proporção de Fibonacci, o que eu pessoalmente acho uma delicinha e na minha visão é a definição máxima de *"ordem e progresso"* 👍 

![New Project (1)](https://user-images.githubusercontent.com/4248081/83680551-f6f23500-a595-11ea-9099-7a7071c6fa35.png)

E como o @lucianopf apontou, o logo também sinaliza a natureza de *componentes* do projeto, em que foi componentizado até a versão de cada API.  Massinha né?

Bom, eu preciso gravar um vídeo para o canal daqui a pouco, mas em seguida eu já quero colocar essas coisas no ar 🤝 vamo que vamo turma!!!! 😍

**Comment by CarlosZiegler** [comment]
Show, ainda vou contribuir nesse projeto hahah.

Em qua, 3 de jun de 2020 22:22, Filipe Deschamps <notifications@github.com>
escreveu:

**Comment by wilsonneto-dev** [comment]
Que massa!! Parabéns!
Já vou procurar aqui nas issues como eu posso contribuir para este projeto que vai ser muito massa!

Parabéns a todos os envolvidos até aqui, e @filipedeschamps obrigado por compartilhar tanto conhecimento conosco.

Abraços!

**Comment by viniciusleitelima** [comment]
Parabéns a todos. Me coloco a disposição para contribuir também

**Comment by lucianopf** [comment]
Sério Vercel é só ❤️ !!!

@paulogdm pfv manda um super thanks pra todo mundo da empresa, a galera ta mandando muito bem!! 🎉 ❤️  🔝 


(Só sinto falta ainda de umas métricas já prontinhas na dash, mas basta ligar numa ferramenta de logs e isso tudo é resolvido, inclusive **parabéns** pra quem desenvolveu os log drains!!!!)
