### ISSUE TITLE
Habilitar CORS no serviço

### ISSUE THREAD

**Issue by lucianopf** [filipedeschamps/BrasilAPI#9]
# Descrição

Precisamos explicitamente habilitar o CORS `*` no serviço para que outras pessoas consigam integrar sem problemas em seus sites

<img width="1680" alt="Screen Shot 2020-01-31 at 10 33 55" src="https://user-images.githubusercontent.com/8251208/73543268-550ae200-4415-11ea-933d-0e8821844db0.png">

Provavelmente a melhor solução pra gente tratar esses headers de config padrão é usar o arquivo de config com as rotas definidas 🤔 

https://zeit.co/docs/configuration#routes/headers

**Comment by OtavioCapila** [comment]
Pensei em algo, mas não testei para ver se realmente funciona.
Mas seria algo parecido com isso ↓
![image](https://user-images.githubusercontent.com/29285724/74439371-dec1a300-4e4a-11ea-9c00-2fc07e7fa97f.png)

Esse código ficaria em um `index.js` na raiz da pasta `pages`. Seria necessário "somente" arrumar alguma forma de executar esse index.
Desta forma não precisaria adicionar o `cors` em todos os endpoints de forma manual.

Só uma idéia mesmo,não sei se é válido.

**Comment by lucas-eduardo** [comment]
@lucianopf @filipedeschamps 

Fiz uma implementação e já realizei o teste sobre essa issue...o PR aberto foi: https://github.com/filipedeschamps/BrasilAPI/pull/17

Fiz um custum server para essa configuração conforme a documentação do next fala.

**Comment by filipedeschamps** [comment]
Show!!! Eu comentei algo importante lá no seu PR 👍

**Comment by filipedeschamps** [comment]
Showww @OtavioCapila !! Eu não sei qual os padrões dos projetos nesse caso, sou super novo no framework, mas me parece mais previsível para evolução do framework fazer manualmente em cada endpoint ou nas configs 👍 Mas muito legal a sua sugestão e dentro de um ecossistema Node.js normal isso faz sentido 🤝 Vou lhe adicionar como contribuidor, pois querendo ou não, isso é colocar a mão na massa!

**Comment by lucas-eduardo** [comment]
@filipedeschamps @OtavioCapila 

Estou em contato com o pessoal do next js e perguntei sobre o custom server ou alguma forma de colocar de modo global os middlewares...obtive a seguinte resposta:

> Hi there
> 
> We don't have global middlewares because those are bad, we don't like the side effects of that, and they also don't work for serverless functions, every function is independant, same for static pages
> 
> And having a custom server is worse so try to avoid that
> 
> let's say you're using API routes for your API
> 
> if you want to add CORS to them
> 
> go to every API route and add it
> 
> there's nothing more to it

Ainda estou em contato com eles, pois fiz a implementação como esta na documentação deles do micro-cors e o mesmo não funcionou quando é gerado o build, só funcionando com o npm run dev...obtendo novidades, trago aqui galera.

**Comment by lucianopf** [comment]
Dúvida sincera:

Por que estamos usando o `Next.js` ao invés de só usar o `Now`? 🤔
A estrutura é totalmente só que é infinitamente mais simples fazer as configurações das funções usando o `now.json`.

A desvantagem seria não ter toda a renderização mágica do Next, mas se o projeto foi apenas uma homepage e um monte de APIs isso não faria muita diferença, correto? 😬 

(To me questionando isso há algum tempo já, e provavelmente estou perdendo algum detalhe importante 😬 )

**Comment by lucianopf** [comment]
Li bastante das docs do Next e realmente parece que a forma que vc fez é a certa @lucas-eduardo !!

Lendo um pouco a lib do `micro-cors` da pra entender bem que ele na verdade é só uma high order function que injeta os headers no nosso futuro response 😬 

Lí tbm sobre o custom server, mas acredito que não é necessário adicionar tanta complexidade só pra ter um comportamento global que podemos sempre ter importando o arquivo que vc gerou de config 😬

**Comment by filipedeschamps** [comment]
E pra testar isso turma? Como vamos fazer? 😂 Acho que não vamos ter como escapar de fazer um E2E nervoso usando a URL de preview deles.

**Comment by lucianopf** [comment]
Então, da pra fazer integration tbm, o que a lib faz é simplesmente injetar uns headers no primeiro parâmetro da função, a gnt consegue mockar essas chamadas passando uns objetos direto pra função como req e res :thinking: 

(Mas de qualquer forma nao descarto e2e tbm não hahaha)

**Comment by filipedeschamps** [comment]
Tudo isso já foi feito, inclusive consegue ser testado e garantido pelos testes E2E desse repositório aqui: https://github.com/filipedeschamps/BrasilAPI/pull/29
